; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Vertex3D Project Creator"
#define MyAppVersion "1.0"
#define MyAppPublisher "VexWare Technologies"
#define MyAppURL "http://www.vexwaretech.com/"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{7401CEB8-812A-473F-A53A-E89E5F33D2C7}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName=C:\Program Files\Vertex3D\Projects\MyProject
DefaultGroupName=MyProject
AllowNoIcons=yes
OutputDir=C:\Users\catch_000\Documents\GitHub\Vertex3DEngine\Vertex3D Engine\SystemAssets
OutputBaseFilename=setup
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: "C:\Users\catch_000\Documents\GitHub\Vertex3DEngine\Vertex3D Engine\Vertex3DModels\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

